### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by uniqueck**
prepare a structure to use update mechanism from fhem like this:
update all https://raw.githubusercontent.com/uniqueck/esp_rgbww_fhemmodule/develop/controls_ledcontroller.txt
add script prepare_update.sh to create changed file with git logs

### CODE REVIEW

**Comment by patrickjahns** [comment]
can you squash the commit c87ca71 so we can have a clean merge

**Comment by uniqueck** [comment]
how can i achieve that

**Comment by patrickjahns** [comment]
either use `git rebase -i master` or `git rebase -i HEAD~2` - also see:

https://git-scm.com/docs/git-rebase
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by uniqueck** [comment]
there is no commit [c87ca71](https://github.com/patrickjahns/esp_rgbww_fhemmodule/commit/c87ca7123c39d06c38edb660409ae2124646f5ec) present
i close the pr and discard all changes and start a new pr

**Pull request closed without merging**
